import Head from "next/head";
import { useState, useEffect } from "react";
import styles from "../../styles/Home.module.css";

export default function Assess() {
  const [data, setData] = useState(null);
  const [isLoading, setLoading] = useState(false);
  useEffect(() => {
    setLoading(true);
    fetch("http://localhost:8000/api/questions")
      .then((res) => res.json())
      .then((data) => {
        setData(data);
        setLoading(false);
      });
  }, []);
  if (isLoading) return <p>Loading...</p>;
  if (!data) return <p>No profile data</p>;
  return (
    <div className={styles.container}>
      <Head>
        <title>Learn</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Learn</h1>
        <div className={styles.grid}>
          {data.map((q) => (
            <a
              href="https://nextjs.org/docs"
              className={styles.card}
              key={q.id}
            >
              <h2>{q.category}</h2>
              <p>{q.question}</p>
            </a>
          ))}
        </div>
      </main>
    </div>
  );
}
