import Link from "next/link";
import Head from "next/head";
import { useState, useEffect } from "react";
import BarChart from "../../components/BarChart";
import styles from "../../styles/Home.module.css";
import LineChart from "../../components/LineChart";

const test_data = {
  name: "Dany",
  LastName: "Pineault",
  age: 45,
  salary: 75000,
  contribution: 7,
};
export default function Evaluate() {
  const weight = [4, 5, 6, 9, 11, 14, 17, 22, 34];
  const [data, setData] = useState(null);
  const [isLoading, setLoading] = useState(false);
  useEffect(() => {
    setLoading(true);
    fetch("http://127.0.0.1:8000/postCalcResults", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(test_data),
    })
      .then((res) => res.json())
      .then((data) => {
        setData(data);
        setLoading(false);
        console.log(data);
      });
  }, []);

  if (isLoading) return <p>Loading...</p>;
  if (!data) return <p>No profile data</p>;
  return (
    <div className={styles.container}>
      <Head>
        <title>Evaluate</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className="">
        <div className="flex flex-row">
          <div className="flex flex-col w-2/4">
            <h1 className="">Welcome to Evaluate</h1>
            <Link href="/evaluate/create">Create a new Scenarion</Link>
          </div>
          <div className="w-2/4 max-h-30">
            <div>
              <BarChart input_data={data}></BarChart>
            </div>
            <div>
              <LineChart input_data={data}></LineChart>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
