import Head from "next/head";
import styles from "../../styles/Home.module.css";

export default function Optimize() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Optimize</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Optimize</h1>
      </main>
    </div>
  );
}
